# Generated by Django 3.0.3 on 2020-02-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Helper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='ans',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcq',
            name='opt1',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcq',
            name='opt2',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcq',
            name='opt3',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcq',
            name='opt4',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mcq',
            name='que',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
