# Generated by Django 3.0.3 on 2020-02-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Helper', '0002_auto_20200221_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='ans',
            field=models.IntegerField(),
        ),
    ]
