# Generated by Django 3.0.3 on 2020-02-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Helper', '0006_auto_20200225_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='upload',
        ),
        migrations.AddField(
            model_name='pdf',
            name='types',
            field=models.CharField(choices=[('IAT1', 'IAT-1'), ('IAT2', 'IAT-2'), ('UNI', 'University Past Paper'), ('PRELIM', 'Prelims'), ('TUTORIAL', 'Tutorial'), ('TT', 'Time Table')], default=0, max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdf',
            name='uploadans',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='pdf',
            name='uploadque',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdf',
            name='year',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pdf',
            name='subject',
            field=models.CharField(blank=True, choices=[('MATHS', 'Maths'), ('BEE', 'BEE'), ('MECHANICS', 'Mechanics'), ('PHYSICS', 'Physics'), ('CHEMISTRY', 'Chemistry')], max_length=9),
        ),
    ]
