# Generated by Django 3.0.3 on 2020-02-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Helper', '0007_auto_20200226_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='subject',
            field=models.CharField(choices=[('MATHS', 'Maths'), ('BEE', 'BEE'), ('MECHANICS', 'Mechanics'), ('PHYSICS', 'Physics'), ('CHEMISTRY', 'Chemistry')], max_length=9),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='types',
            field=models.CharField(choices=[('IAT1', 'IAT-1 Paper'), ('IAT2', 'IAT-2 Paper'), ('UNI', 'University Past Paper'), ('PRELIM', 'Prelims Papers'), ('TUTORIAL', 'Tutorial'), ('TT', 'Time Table')], max_length=9),
        ),
    ]
