# Generated by Django 3.0.3 on 2020-02-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Helper', '0008_auto_20200226_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='upload',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
